POS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sisventas.urls')),
]

sisventas/urls.py
from django.urls import path
from .views import *
from . import views
from django.contrib import admin

app_name = 'sisventas'
urlpatterns = [
    path('', views.loginpage, name='login'),
    path('admin/', admin.site.urls),
    path('logout/', views.logout_view, name='logout'),
    path('inicio/', views.base, name='base'),
    path('pos/', views.pos, name='pos_system'),
    path('document/<int:sale_id>', views.document, name='document'),
    path('search-products/', views.search_products, name='search-products'),
    path('search-inventory/', views.search_inventory, name='search-inventory'),
    path('formprod/', views.form_product, name='form_prod'),
    path('delete/<int:id>/', views.form_product_delete, name='prod_delete'),
    path('edit/<int:id>/', views.form_product_edit, name='prod_edit'),
    path('addcart/<int:id>/', views.add_product_cart, name='add_cart'),
    path('remove/<int:id>/', views.remove_product_cart, name='remove_cart'),
    path('updatecart/<int:id>/', views.update_cart, name='update_cart'),
    path('clear/', views.clear_cart, name='clear_cart'),
    path('confirm/', views.confirm_sale, name='confirm_sale'),
    path('formclient/', views.form_client, name='form_client'),
    path('deleteclient/<str:rut>/', views.form_client_delete, name='client_delete'),
    path('editclient/<str:rut>/', views.form_client_edit, name='client_edit'),
    path('search-client/', views.search_client, name='search-client'),
    path('sales_jefe_ventas/', views.sales_jefe_ventas, name='sales_jefe_ventas'),
    path('sales_vendedor/', views.sales_vendedor, name='sales_vendedor'),
    path('search-sale/', views.search_sale, name='search-sale'),
    path('sale_detail/<int:sale_id>', views.sale_detail, name='sale_detail'),
    path('refund/', views.refund, name='refund'),
    path('change_product/<int:sale_id>/',
         views.change_product, name='change_product'),
    path('change_product/', views.change_product, name='change_product_no_id'),
    path('search-change/', views.search_products_change, name='search_in_change'),
    path('genre/', views.genre, name='genre'),
    path('genre_delete/<int:id>/', views.genre_delete, name='genre_delete'),
    path('genre_edit/<int:id>/', views.genre_edit, name='genre_edit'),
    path('region_delete/<int:id>/', views.region_delete, name='region_delete'),
    path('region_edit/<int:id>/', views.region_edit, name='region_edit'),
    path('ciudad_delete/<int:id>/', views.ciudad_delete, name='ciudad_delete'),
    path('ciudad_edit/<int:id>/', views.ciudad_edit, name='ciudad_edit'),
    path('comuna_delete/<int:id>/', views.comuna_delete, name='comuna_delete'),
    path('comuna_edit/<int:id>/', views.comuna_edit, name='comuna_edit'),
    path('form_location/', views.form_location, name='form_location'),
    path('jefe_ventas/', views.jefe_ventas, name='jefe_ventas'),
    path('jefe_search/', views.search_jefe_ventas, name='jefe_search'),
    path('auth/', views.auth, name='auth'),
    path('authorization/', views.authorization, name='authorization'),
    path('delete_sale_id/', views.delete_sale_id, name='delete_sale_id'),
    path('start_sale/', views.start_day, name='start_sale'),
    path('end_sale/', views.end_day, name='end_sale'),
    path('form_employee/', views.form_employee, name='form_employee'),
    path('edit_employee/<str:rut>/',
         views.form_employee_edit, name='edit_employee'),
    path('delete_employee/<str:rut>/',
         views.form_employee_delete, name='delete_employee'),
    path('profile/', views.profile, name='profile'),
    path('profile_edit/<int:id>', views.profile_edit, name='edit_profile'),
    path('profile_delete/<int:id>', views.profile_delete, name='delete_profile'),
    path('iva/', views.iva, name='iva'),
    path('iva_edit/<int:id>/', views.iva_edit, name='iva_edit'),
    path('iva_delete/<int:id>/', views.iva_delete, name='iva_delete'),
    path('registro_empleados/', views.working_hours, name='registro_empleados'),
    path('credentials/', views.change_credentials, name='credentials'),
    path('return_page/', views.return_page, name='return_page'),
    path('sales_report/', views.sales_report, name='sales_report'),
    path('open_close/', views.open_close_list, name='open_close'),

]

sisventas/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Product, SaleDetail, Sale, Document, Person, IVA, EmployeeRegister, Genre, Profile, Commune, City, Region, OpeningClosing, EmployeeRegister
from .forms import Form_product, Form_client, Form_genre, Form_region, Form_ciudad, Form_comuna, Form_employee, Form_profile, Form_iva, CustomPasswordChangeForm
from .cart import Cart
from .util import total_cart
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string, get_template
from django.views.decorators.http import require_GET
from django.urls import reverse
from xhtml2pdf import pisa
from django.http import HttpResponseForbidden
from django.contrib.auth import update_session_auth_hash
from django.db.models import Sum, F


def profile_required(*required_profile_ids):
    def decorator(view_func):
        @login_required
        def _wrapped_view(request, *args, **kwargs):
            if request.user.person.id_profile.id in required_profile_ids:
                return view_func(request, *args, **kwargs)
            else:
                return HttpResponseForbidden()
        return _wrapped_view
    return decorator


def auth(request):
    return render(request, 'auth.html')


@login_required

def return_page(request):
    employee = request.user.person
    person = Person.objects.all().filter(rut=employee.rut).first()
    if person.id_profile.name == 'Vendedor':
        return redirect('sisventas:form_client')
    elif person.id_profile.name == 'Jefe de Ventas':
        return redirect('sisventas:form_employee')
    elif person.id_profile.name == 'Dueño':
        return redirect('sisventas:form_employee')


@login_required
@profile_required(1, 2, 3)
def authorization(request):
    if request.method == 'POST':
        authuser = request.POST.get('authuser')
        password = request.POST.get('password')
        person = Person.objects.all().filter(rut=authuser).first()
        message = {}
        if person is not None:
            user = authenticate(username=person.email, password=password)
            if user is not None and person.id_profile.id in [2, 3]:
                request.session['is_authorized'] = True
                message = {'authorized': 'true'}
            else:
                request.session['is_authorized'] = False
                message = {'authorized': 'false'}
        else:
            request.session['is_authorized'] = False
            message = {'error': 'Usuario no existe'}
            return JsonResponse(message)
    return JsonResponse(message)


def loginpage(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        person = Person.objects.all().filter(email=username).first()

        if person is None:
            context = {'error': 'Nombre de usuario incorrecto'}
            return render(request, 'login.html', context)
        else:
            if user is not None and user.is_authenticated:
                opening_time = timezone.now().time()
                closing_time = None
                date = timezone.now().date()
                register = EmployeeRegister(
                    opening_time_sesion=opening_time, closing_time_sesion=closing_time, date=date, rut_employee=person)
                register.save()
                login(request, user)
                request.session['register_id'] = register.id
                if person.id_profile.name == 'Vendedor':
                    return redirect('sisventas:pos_system')
                elif person.id_profile.name == 'Jefe de Ventas':
                    return redirect('sisventas:jefe_ventas')
                elif person.id_profile.name == 'Dueño':
                    return redirect('sisventas:jefe_ventas')
            else:
                context = {'error': 'Contraseña incorrecta'}
                return render(request, 'login.html', context)
    return render(request, 'login.html', context)


def logout_view(request):
    register_id = request.session.get('register_id')
    if register_id is not None:
        register = get_object_or_404(EmployeeRegister, id=register_id)
        register.closing_time_sesion = timezone.now().time()
        register.save()
    logout(request)
    return redirect('sisventas:login')


@login_required
@profile_required(1, 2, 3)
def base(request):
    return render(request, 'base.html',)


@login_required
@profile_required(2, 3)
def jefe_ventas(request):
    total = 0
    if request.method == 'POST':
        today_sales = 'today' in request.POST
        week_sales = 'week' in request.POST
        month_sales = 'month' in request.POST
    else:
        today_sales = request.session.get('today', False)
        week_sales = request.session.get('week', False)
        month_sales = request.session.get('month', False)

    request.session['today'] = today_sales
    request.session['week'] = week_sales
    request.session['month'] = month_sales

    sales_list = Sale.objects.all().order_by('-id')
    now = timezone.now()
    if today_sales:
        sales_list = sales_list.filter(
            date__year=now.year, date__month=now.month, date__day=now.day)
        for sale in sales_list:
            total += sale.total
    elif week_sales:
        start_week = now - timezone.timedelta(days=now.weekday())
        end_week = start_week + timezone.timedelta(days=7)
        sales_list = sales_list.filter(date__range=[start_week, end_week])
        for sale in sales_list:
            total += sale.total

    else:
        sales_list = sales_list.filter(
            date__year=now.year, date__month=now.month)
        for sale in sales_list:
            total += sale.total

    paginator = Paginator(sales_list, 12)
    page_number = request.GET.get('page')
    sales = paginator.get_page(page_number)
    context = {
        'sales': sales,
        'total': total,
    }
    return render(request, 'jefe_ventas.html', context)


@login_required
@profile_required(2, 3)
def search_jefe_ventas(request):
    search_term = request.GET.get('search')
    if request.method == 'POST':
        today_sales = 'today' in request.POST
        week_sales = 'week' in request.POST
        month_sales = 'month' in request.POST
    else:
        today_sales = request.session.get('today', False)
        week_sales = request.session.get('week', False)
        month_sales = request.session.get('month', False)

    request.session['today'] = today_sales
    request.session['week'] = week_sales
    request.session['month'] = month_sales

    sales_list = Sale.objects.all()
    now = timezone.now()
    if today_sales:
        sales_list = sales_list.filter(
            date__year=now.year, date__month=now.month, date__day=now.day)
        if search_term.isdigit():
            sales_list = sales_list.filter(
                id__icontains=search_term).order_by('date')
        else:
            sales_list = sales_list.filter(
                seller__name__icontains=search_term).order_by('date')

    elif week_sales:
        start_week = now - timezone.timedelta(days=now.weekday())
        end_week = start_week + timezone.timedelta(days=7)
        sales_list = sales_list.filter(date__range=[start_week, end_week])
        if search_term.isdigit():
            sales_list = sales_list.filter(
                id__icontains=search_term).order_by('date')
        else:
            sales_list = sales_list.filter(
                seller__name__icontains=search_term).order_by('date')

    else:
        sales_list = sales_list.filter(
            date__year=now.year, date__month=now.month)
        if search_term.isdigit():
            sales_list = sales_list.filter(
                id__icontains=search_term).order_by('date')
        else:
            sales_list = sales_list.filter(
                seller__name__icontains=search_term).order_by('date')

    paginator = Paginator(sales_list, 12)
    page_number = request.GET.get('page')
    sales = paginator.get_page(page_number)
    context = {
        'sales': sales,
    }
    return render(request, 'sales_list.html', context)


@login_required
@profile_required(2, 3)
def start_day(request):
    employee = request.user.person
    is_open = OpeningClosing.objects.filter(
        date=timezone.now().date(), is_open=True).exists()
    if not is_open:
        OpeningClosing.objects.create(
            opening_time=timezone.now(),
            date=timezone.now().date(),
            opening_employee=employee,
            is_open=True
        )

    return redirect('sisventas:jefe_ventas')


@login_required
@profile_required(2, 3)
def end_day(request):
    employee = request.user.person
    day = OpeningClosing.objects.get(
        date=timezone.now().date(), is_open=True)
    if day.is_open:
        day.closing_time = timezone.now()
        day.closing_employee = employee
        day.is_open = False
        day.save()

    return redirect('sisventas:jefe_ventas')


@login_required
@profile_required(1)
def pos(request):
    products_list = Product.objects.filter(is_hidden=False).order_by('id')
    paginator = Paginator(products_list, 10)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)
    get_documents = Document.objects.all().order_by('id')
    documents = []
    for document in get_documents:
        if document.id != 3:
            document = document
            documents.append(document)
    employee = request.user.person
    clients = Person.objects.filter(
        is_employee=False, is_active=True).order_by('rut')
    sales = Sale.objects.filter(

sisventas/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  <head>
    <link rel="icon" href="{% static '../static/img/shopping.svg' %}" />
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/pos.css' %}" />
    <title>{% block titulo %}{% endblock %}</title>
  </head>

  <body>
    {% csrf_token %}
    <nav class="navbar bg-dark border-bottom border-bottom-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
        <div class="d-flex">
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarText"
            aria-controls="navbarText"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% block navbar_jefe_ventas %}{% endblock %} {% block navbar_vendedor %}{% endblock %}
            </ul>
          </div>
        </div>
        <div class="d-flex">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item me-5">
              <a class="nav-link" href="{% url 'sisventas:credentials' %}">Cambiar de contraseña</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'sisventas:logout' %}">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">{% block contenido %}{% endblock %}</div>
  </body>
  <br /><br />
  <footer class="pt-3 mt-5 text-body-secondary border-top p-5">&copy; 2023</footer>
</html>

sisventas/templates/form_employee.html
{% extends 'base.html' %} {% load static %} {% block titulo %} Formulario Empleados {% endblock %} {% csrf_token %} {% block navbar_jefe_ventas %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:jefe_ventas' %}">Inicio</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:form_prod' %}">Inventario</a>
</li>

<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:form_employee' %}">Empleados</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:registro_empleados' %}">Registro de Empleados</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:sales_report' %}">Informe de Ventas</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:open_close' %}">Registro de Apertura y Cierre</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:sales_jefe_ventas' %}">Todas las Ventas</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:iva' %}">IVA</a>
</li>
{% load extras %} {% endblock %} {% block contenido %}
<div>{% include 'auth.html' %}</div>

<div class="container py-4">
  <div class="mb-4 mt-3 rounded-4 shadow">
    <div class="container-fluid">
      <h6 class="fw-bold mb-5 fs-2 text-center">Empleados</h6>
      <div class="row">
        <div class="col">
          <div class="search mb-2">
            <input type="text" class="form-control" id="search-input" placeholder="Ingrese nombre del cliente" />
          </div>
          <table class="table table-striped table-hover border table-prod-invent" id="table-clients">
            <thead>
              <tr>
                <th>Rut</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Género</th>
                <th>Fecha Nac.</th>
                <th>Teléfono</th>
                <th>Email</th>
                <th>Razon social</th>
                <th>Giro</th>
                <th>Estado</th>
                <th>Perfil</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% include 'employee_list.html' %}
            </tbody>
          </table>
        </div>
        <div class="col">
          <form enctype="multipart/form-data" method="post" class="confirm-employee" id="formEmployee">
            {% csrf_token %}
            <input type="hidden" id="isAuthorized" name="isAuthorized" />
            <table class="table table-borderless">
              <thead>
                <tr>
                  <th>Campo</th>
                  <th>Valor</th>
                </tr>
              </thead>
              <tbody>
                {% for campo in form %}
                <tr>
                  <td>
                    <label class="form-label">{{ campo.label }}<span class="text-danger">*</span></label>
                  </td>
                  <td class="align-middle">
                    <div class="d-flex align-items-center gap-3">
                      {% if campo.label == "Género" %}{{ campo }}
                      <a href="{% url 'sisventas:genre' %}">
                        <img src="{% static '/img/plus-circle.svg' %}" height="22px" width="22px" />
                      </a>
                    </div>

                    <div class="d-flex align-items-center gap-3">
                      {% elif campo.label == "Región" %} {{ campo }}
                      <a href="{% url 'sisventas:form_location' %}">
                        <img src="{% static '/img/plus-circle.svg' %}" height="22px" width="22px" />
                      </a>

                      {% elif campo.label == "Ciudad" %} {{ campo }}
                      <a href="{% url 'sisventas:form_location' %}">
                        <img src="{% static '/img/plus-circle.svg' %}" height="22px" width="22px" />
                      </a>
                      {% elif campo.label == "Comuna" %} {{ campo }}
                      <a href="{% url 'sisventas:form_location' %}">
                        <img src="{% static '/img/plus-circle.svg' %}" height="22px" width="22px" />
                      </a>
                      </a>
                      {% elif campo.label == "ID del perfil" %} {{ campo }}
                      <a href="{% url 'sisventas:profile' %}">
                        <img src="{% static '/img/plus-circle.svg' %}" height="22px" width="22px" />
                      </a>
                      {% else %} {{ campo }} {% endif %}
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <div class="d-flex justify-content-center">
              <div type="submit" class="btn">
                {% if edit_mode %}
                <button class="btn btn-success btn-lg add-employee">Actualizar Empleado</button>
                {% else %}
                <button class="btn btn-success btn-lg add-employee">Ingresar Empleado</button>
                {% endif %}
              </div>
              <div type="reset" value="reset" class="btn">
                <a class="btn btn-danger btn-lg" id="reset-employee" href="{% url 'sisventas:form_employee' %}"> Limpiar Campos </a>
              </div>
            </div>
          </form>
          {% if messages %}
          <div class="alert alert-danger">
            <ul>
              {% for message in messages %}
              <li>{{ message }}</li>
              {% endfor %}
            </ul>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

sisventas/templates/iva.html
{% extends 'base.html' %} {% load static %} {% block titulo %} Añadir IVA {% endblock %} {% csrf_token %} {% block navbar_jefe_ventas %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:jefe_ventas' %}">Inicio</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:form_prod' %}">Inventario</a>
</li>

<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:form_employee' %}">Empleados</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:registro_empleados' %}">Registro de Empleados</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:sales_report' %}">Informe de Ventas</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:open_close' %}">Registro de Apertura y Cierre</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:sales_jefe_ventas' %}">Todas las Ventas</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:iva' %}">IVA</a>
</li>
{% load extras %} {% endblock %} {% block contenido %}

<body>
  <div class="container h-100">
    <div class="position-static d-block p-4 py-md-5" tabindex="-1" role="dialog" id="modalSignin">
      <div class="modal-dialog" role="document">
        <div class="modal-content rounded-4 shadow p-4">
          <h5 class="fw-bold mb-0 fs-2 mb-3 text-center mt-2">IVA</h5>
          <table class="table table-hover" id="table-iva">
            <thead>
              <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for iva in ivas %}
              <tr>
                <td class="align-middle">{{ iva.id }}</td>
                <td class="align-middle">{{ iva.value }}</td>
                <td class="d-flex justify-content-center justify-content-end">
                  <a class="delete-iva mx-3" href="{% url 'sisventas:iva_delete' iva.id %}">
                    <img src="{% static '/img/trash3.svg' %}" />
                  </a>
                  <a class="edit-iva" href="{% url 'sisventas:iva_edit' iva.id %}">
                    <img src="{% static '/img/pencil.svg' %}" />
                  </a>
                </td>
              </tr>
            </tbody>

            {% empty %}
            <tr>
              <td colspan="6">No hay IVA</td>
            </tr>
            {% endfor %}
          </table>
          <form method="post" id="iva-form">
            {% csrf_token %}
            <table class="table table-borderless">
              <thead>
                <tr>
                  <th>Campo</th>
                  <th>Valor</th>
                </tr>
              </thead>
              <tbody>
                {% for campo in form %}
                <tr>
                  <td class="align-middle">
                    <label class="form-label"> {{ campo.label }}</label>
                  </td>
                  <td class="align-middle">
                    <div class="input-iva">{{ campo }}</div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <div class="d-flex justify-content-center">
              <div>
                {% if edit_mode %}
                <button type="submit" class="btn btn-success btn-sm mb-3 mx-2 update-iva">Actualizar IVA</button>
                {% else %}
                <button type="submit" class="btn btn-success btn-sm mb-3 mx-2 add-iva">Ingresar</button>
                {% endif %}
              </div>
              <div type="reset" value="reset" class="mx-2">
                <a class="btn btn-danger btn-sm" id="reset-iva" href="{% url 'sisventas:iva' %}"> Limpiar Campos </a>
              </div>
            </div>
          </form>
          <div class="d-flex justify-content-start">
            <a class="btn" onclick="goBack()">
              <img src="{% static '/img/arrow-left-circle-fill.svg' %}" height="25px" width="25px" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    function goBack() {
      window.history.back();
    }
  </script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{% static 'js/confirmforms.js' %}"></script>
</body>

{% endblock %} ```

sisventas/templates/profile.html
{% extends 'base.html' %} {% load static %} {% block titulo %} Añadir Perfil {% endblock %} {% csrf_token %} {% block navbar_jefe_ventas %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:jefe_ventas' %}">Inicio</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:form_prod' %}">Inventario</a>
</li>

<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:form_employee' %}">Empleados</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:registro_empleados' %}">Registro de Empleados</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:sales_report' %}">Informe de Ventas</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:open_close' %}">Registro de Apertura y Cierre</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:sales_jefe_ventas' %}">Todas las Ventas</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'sisventas:iva' %}">IVA</a>
</li>
{% load extras %} {% endblock %} {% block contenido %}

<body>
  <div class="container h-100">
    <div class="position-static d-block p-4 py-md-5" tabindex="-1" role="dialog" id="modalSignin">
      <div class="modal-dialog" role="document">
        <div class="modal-content rounded-4 shadow p-4">
          <h5 class="fw-bold mb-0 fs-2 mb-3 text-center mt-2">Perfil de Cargo</h5>
          <table class="table table-hover" id="table-profile">
            <thead>
              <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for profile in profiles %}
              <tr>
                <td class="align-middle">{{ profile.id }}</td>
                <td class="align-middle">{{ profile.name }}</td>
                <td class="d-flex justify-content-center justify-content-end">
                  <a class="delete-profile mx-3" href="{% url 'sisventas:delete_profile' profile.id %}">
                    <img src="{% static '/img/trash3.svg' %}" />
                  </a>
                  <a class="edit-profile" href="{% url 'sisventas:edit_profile' profile.id %}">
                    <img src="{% static '/img/pencil.svg' %}" />
                  </a>
                </td>
              </tr>
            </tbody>

            {% empty %}
            <tr>
              <td colspan="6">No hay Perfiles</td>
            </tr>
            {% endfor %}
          </table>
          <form method="post" id="profile-form">
            {% csrf_token %}
            <table class="table table-borderless">
              <thead>
                <tr>
                  <th>Campo</th>
                  <th>Valor</th>
                </tr>
              </thead>
              <tbody>
                {% for campo in form %}
                <tr>
                  <td class="align-middle">
                    <label class="form-label"> {{ campo.label }}</label>
                  </td>
                  <td class="align-middle">
                    <div class="input-profile">{{ campo }}</div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <div class="d-flex justify-content-center">
              <div>
                {% if edit_mode %}
                <button type="submit" class="btn btn-success btn-sm mb-3 mx-2 update-profile">Actualizar Perfil</button>
                {% else %}
                <button type="submit" class="btn btn-success btn-sm mb-3 mx-2 add-profile">Ingresar Perfil</button>
                {% endif %}
              </div>
              <div type="reset" value="reset" class="mx-2">
                <a class="btn btn-danger btn-sm" id="reset-profile" href="{% url 'sisventas:profile' %}"> Limpiar Campos </a>
              </div>
            </div>
          </form>
          <div class="d-flex justify-content-start">
            <a class="btn" onclick="goBack()">
              <img src="{% static '/img/arrow-left-circle-fill.svg' %}" height="25px" width="25px" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    function goBack() {
      window.history.back();
    }
  </script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{% static 'js/confirmforms.js' %}"></script>
</body>

{% endblock %} ```